/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { BookmarkInterface } from "./interfaces/bookmark.interface";
export namespace Components {
    interface AddForm {
    }
    interface AppBookmark {
        "bookmark": BookmarkInterface;
    }
    interface AppHome {
    }
    interface AppRoot {
    }
    interface BookamrksWrapper {
        "bookmarks": BookmarkInterface[];
    }
}
declare global {
    interface HTMLAddFormElement extends Components.AddForm, HTMLStencilElement {
    }
    var HTMLAddFormElement: {
        prototype: HTMLAddFormElement;
        new (): HTMLAddFormElement;
    };
    interface HTMLAppBookmarkElement extends Components.AppBookmark, HTMLStencilElement {
    }
    var HTMLAppBookmarkElement: {
        prototype: HTMLAppBookmarkElement;
        new (): HTMLAppBookmarkElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLBookamrksWrapperElement extends Components.BookamrksWrapper, HTMLStencilElement {
    }
    var HTMLBookamrksWrapperElement: {
        prototype: HTMLBookamrksWrapperElement;
        new (): HTMLBookamrksWrapperElement;
    };
    interface HTMLElementTagNameMap {
        "add-form": HTMLAddFormElement;
        "app-bookmark": HTMLAppBookmarkElement;
        "app-home": HTMLAppHomeElement;
        "app-root": HTMLAppRootElement;
        "bookamrks-wrapper": HTMLBookamrksWrapperElement;
    }
}
declare namespace LocalJSX {
    interface AddForm {
    }
    interface AppBookmark {
        "bookmark"?: BookmarkInterface;
    }
    interface AppHome {
    }
    interface AppRoot {
    }
    interface BookamrksWrapper {
        "bookmarks"?: BookmarkInterface[];
    }
    interface IntrinsicElements {
        "add-form": AddForm;
        "app-bookmark": AppBookmark;
        "app-home": AppHome;
        "app-root": AppRoot;
        "bookamrks-wrapper": BookamrksWrapper;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "add-form": LocalJSX.AddForm & JSXBase.HTMLAttributes<HTMLAddFormElement>;
            "app-bookmark": LocalJSX.AppBookmark & JSXBase.HTMLAttributes<HTMLAppBookmarkElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "bookamrks-wrapper": LocalJSX.BookamrksWrapper & JSXBase.HTMLAttributes<HTMLBookamrksWrapperElement>;
        }
    }
}
